<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f62a9957-0d73-43d3-81f3-29d6fa1e8ae4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "No" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
